module.exports = [
	[/\b(nah|nope)\b/gi,									"no,"],
	[/\b(ye|yeah|yep|yah|aye|yea)\b/gi,						"yes,"],
	[/^ya$/gi,												"yes"],
	[/\b(srlsy)\b/gi,										"seriously"],
	[/\b(y)\b/gi,											"why"],
	[/\b(k|okay|o\.k\.|oki|okey-dokey|okey-doke)\b/gi,		"ok"],
	[/\b(alrighty)\b/gi,									"alright"],
	[/\b('em)\b/gi,											"them"],
	[/\b(u|ya|yah)\b/gi,									"you"],
	[/^(yo)$/gi,											"you"],
	[/\b(yo)\b/gi,											"your"],
	[/\b(cuz|b\/c)\b/gi,									"because"],
	[/\b(pls|plz|pwez)\b/gi,								"please,"],
	[/\b(pw(e)+z)\b/gi,										"please,"],
	[/\b(dis)\b/gi,											"this"],
	[/\b(2moro|2mro|2mr)\b/gi,								"tomorrow"],
	[/\b(2nt|2nite|tnite)\b/gi,								"tonight"],
	[/\b(gr8)\b/gi,											"great"],
	[/\b(l8r|l8tr)\b/gi,									"later"],
	[/\b(tnx|thks|tx|tnx|tanx|thanks|thanx)\b/gi,			"thank you"],
	[/\b(r|'re)\b/gi,										"are"],
	[/\b('m)\b/gi,											"am"],
	[/\b(hi|hey)\b/gi,										"hello"],
	[/\b(<3)\b/gi,											"love"],
	[/\b(bae)\b/gi,											"babe"],
	[/\b(dafuq)\b/gi,										"what the fuck"],
	[/\b(dm)\b/gi,											"direct message"],
	[/\b(eli5)\b/gi,										"explain like I am 5 years old"],
	[/\b(fml)\b/gi,											"fuck my life"],
	[/\b(facepalm|smh)\b/gi,								"ugh"],
	[/\b(imo|imho)\b/gi,									"in my opinion"],
	[/\b(irl)\b/gi,											"in real life"],
	[/\b(jsyk)\b/gi,										"just so you know"],
	[/\b(lol|lolz|lulz|lmao|lmfao|rofl|roflmao|roflol)\b/gi,"haha"],
	[/\b(haha)+\b/gi,										"haha"],
	[/\b(hehe)+\b/gi,										"haha"],
	[/\bl(o|u)+l(z|s)?\b/gi,								"haha"],
	[/\b(nsfw)\b/gi,										"not safe for work"],
	[/\b(tl:?dr;?)\b/gi,									"it's too long, I didn't read it"],
	[/\b(yo+lo+)\b/gi,										"You only live once"],
	[/\b(idk)\b/gi,											"I don't know"],
	[/\b(tbh)\b/gi,											"to be honest"],
	[/\b(milf)\b/gi,										"mother I like to fuck"],
	[/\b(filf)\b/gi,										"father I like to fuck"],
	[/\b(dilf)\b/gi,										"dad I like to fuck"],
	[/\b(g4(bi)?d)\b/gi,									"god forbid"],
	[/\b(ikr?)\b/gi,										"right"],
	[/\b(sup( (sun|son|sis))?)\b/gi,						"how are you"],
	[/\b(sh\*t|shi+t|sh!t)e?\b/gi,							"shit"],
	[/\bf(\*\*|@c|u|u+c|\*c|u\*)k/gi,						"fuck"],
	[/\b(jk|j\/k)\b/gi,										"just kidding"],
	[/\b(w\/o|w\/t)\b/gi,									"without"],
	[/\b(w\/)\b/gi,											"with"],
	[/\b(outta)\b/gi,										"out of"],
	[/\b(shd)\b/gi,											"should"],
	[/\b(c)\b/gi,											"see"],
	[/!(!)+/gi,												"!"],
	[/\?(\?)+/gi,											"?"],
	[/,(,)+/gi,												"?"],
];